### PR TITLE
Version update 190709

### PR DESCRIPTION
**Pull request by eneufeld**

### CODE REVIEW

**Comment by planger** [comment]
Unfortunately, it doesn't build on my machine. I tried running `./run.sh -b -c -f`. Am I doing something wrong?
Below is the result that I'm getting (the yarn build stops after the line above and fails too).
Code-wise it looks good to me.

<pre>[<font color="#729FCF"><b>INFO</b></font>] <b>--- </b><font color="#4E9A06">tycho-packaging-plugin:1.2.0:validate-id</font> <b>(default-validate-id)</b> @ <font color="#06989A">com.eclipsesource.codegen.application</font><b> ---</b>
[<font color="#729FCF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#729FCF"><b>INFO</b></font>] <b>Reactor Summary:</b>
[<font color="#729FCF"><b>INFO</b></font>] 
[<font color="#729FCF"><b>INFO</b></font>] com.eclipsesource.coffee.parent 0.1.0-SNAPSHOT ..... <font color="#8AE234"><b>SUCCESS</b></font> [  0.222 s]
[<font color="#729FCF"><b>INFO</b></font>] com.eclipsesource.coffee.target 0.1.0-SNAPSHOT ..... <font color="#8AE234"><b>SUCCESS</b></font> [  0.206 s]
[<font color="#729FCF"><b>INFO</b></font>] com.eclipsesource.workflow 0.1.0-SNAPSHOT .......... <font color="#8AE234"><b>SUCCESS</b></font> [  1.424 s]
[<font color="#729FCF"><b>INFO</b></font>] com.eclipsesource.workflow.generator 0.1.0-SNAPSHOT  <font color="#8AE234"><b>SUCCESS</b></font> [  0.252 s]
[<font color="#729FCF"><b>INFO</b></font>] com.eclipsesource.workflow.generator.json 0.1.0-SNAPSHOT <font color="#8AE234"><b>SUCCESS</b></font> [  0.119 s]
[<font color="#729FCF"><b>INFO</b></font>] com.eclipsesource.workflow.generator.java 0.1.0-SNAPSHOT <font color="#8AE234"><b>SUCCESS</b></font> [  5.969 s]
[<font color="#729FCF"><b>INFO</b></font>] com.eclipsesource.coffee.workflow.analyzer 0.1.0-SNAPSHOT <font color="#8AE234"><b>SUCCESS</b></font> [  0.116 s]
[<font color="#729FCF"><b>INFO</b></font>] com.eclipsesource.workflow.dsl 0.1.0-SNAPSHOT ...... <font color="#8AE234"><b>SUCCESS</b></font> [  8.875 s]
[<font color="#729FCF"><b>INFO</b></font>] com.eclipsesource.coffee.workflow.analyzer.json 0.1.0-SNAPSHOT <font color="#8AE234"><b>SUCCESS</b></font> [  0.421 s]
[<font color="#729FCF"><b>INFO</b></font>] com.eclipsesource.coffee.workflow.analyzer.application 0.1.0-SNAPSHOT <font color="#8AE234"><b>SUCCESS</b></font> [  0.305 s]
[<font color="#729FCF"><b>INFO</b></font>] com.eclipsesource.workflow.dsl.parent 1.0.0-SNAPSHOT <font color="#8AE234"><b>SUCCESS</b></font> [  0.014 s]
[<font color="#729FCF"><b>INFO</b></font>] com.eclipsesource.workflow.dsl.ide 1.0.0-SNAPSHOT .. <font color="#8AE234"><b>SUCCESS</b></font> [  5.754 s]
[<font color="#729FCF"><b>INFO</b></font>] com.eclipsesource.codegen.product 0.1.0-SNAPSHOT ... <font color="#8AE234"><b>SUCCESS</b></font> [ 40.867 s]
[<font color="#729FCF"><b>INFO</b></font>] com.eclipsesource.codegen.application 0.1.0-SNAPSHOT <font color="#EF2929"><b>FAILURE</b></font> [  0.008 s]
[<font color="#729FCF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#729FCF"><b>INFO</b></font>] <font color="#EF2929"><b>BUILD FAILURE</b></font>
[<font color="#729FCF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#729FCF"><b>INFO</b></font>] Total time:  02:08 min
[<font color="#729FCF"><b>INFO</b></font>] Finished at: 2019-07-10T10:16:33+02:00
[<font color="#729FCF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#EF2929"><b>ERROR</b></font>] Failed to execute goal <font color="#4E9A06">org.eclipse.tycho:tycho-packaging-plugin:1.2.0:validate-id</font> <b>(default-validate-id)</b> on project <font color="#06989A">com.eclipsesource.codegen.application</font>: <font color="#EF2929"><b>The Maven artifactId (currently: &quot;com.eclipsesource.codegen.application&quot;) must be the same as the bundle symbolic name (currently: &quot;com.eclipsesource.coffee.codegen.java.application&quot;)</b></font> -&gt; <b>[Help 1]</b>
[<font color="#EF2929"><b>ERROR</b></font>] 
[<font color="#EF2929"><b>ERROR</b></font>] To see the full stack trace of the errors, re-run Maven with the <b>-e</b> switch.
[<font color="#EF2929"><b>ERROR</b></font>] Re-run Maven using the <b>-X</b> switch to enable full debug logging.
[<font color="#EF2929"><b>ERROR</b></font>] 
[<font color="#EF2929"><b>ERROR</b></font>] For more information about the errors and possible solutions, please read the following articles:
[<font color="#EF2929"><b>ERROR</b></font>] <b>[Help 1]</b> http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[<font color="#EF2929"><b>ERROR</b></font>] 
[<font color="#EF2929"><b>ERROR</b></font>] After correcting the problems, you can resume the build with the command
[<font color="#EF2929"><b>ERROR</b></font>]   <b>mvn &lt;goals&gt; -rf :com.eclipsesource.codegen.application</b>
[10:16:34.448] Copy built products...
  [10:16:34.450] Copy CodeGen to &apos;web/coffee-java-extension/server&apos;.
  [10:16:34.498] Copy WorkflowAnalyzer to &apos;web/coffee-workflow-analyzer/server&apos;.
  [10:16:34.678] Copy WorkflowDSL to &apos;web/coffee-workflow-analyzer-editors/server&apos;.
[10:16:34.886] Copy finished.
<b>yarn install v1.15.2</b>
<font color="#8D8F8A">[1/4] Resolving packages...</font>
<font color="#8D8F8A">[2/4] Fetching packages...</font>
<font color="#C4A000">warning</font> Pattern [&quot;rimraf@latest&quot;] is trying to unpack in the same destination &quot;/home/philip/.cache/yarn/v4/npm-rimraf-2.6.3-b2d104fe0d8fb27cf9e0a1cda8262dd3833c6cab/node_modules/rimraf&quot; as pattern [&quot;rimraf@^2.6.2&quot;,&quot;rimraf@^2.2.8&quot;,&quot;rimraf@^2.6.2&quot;,&quot;rimraf@2&quot;,&quot;rimraf@^2.6.2&quot;,&quot;rimraf@^2.5.4&quot;,&quot;rimraf@^2.6.3&quot;,&quot;rimraf@^2.2.8&quot;,&quot;rimraf@^2.5.4&quot;,&quot;rimraf@^2.6.1&quot;,&quot;rimraf@^2.6.2&quot;,&quot;rimraf@^2.6.2&quot;]. This could result in non-deterministic behavior, skipping.
<font color="#C4A000">warning</font> package.json: No license field
<font color="#C4A000">warning</font> theia-tree-editor@0.0.6: No license field
<font color="#8D8F8A">[1/4] Resolving packages...</font>
<font color="#C4A000">warning</font> Resolution field &quot;@theia/core@0.7.1&quot; is incompatible with requested version &quot;@theia/core@^0.7.2&quot;
<font color="#C4A000">warning</font> Resolution field &quot;@theia/core@0.7.1&quot; is incompatible with requested version &quot;@theia/core@^0.7.2&quot;
<font color="#C4A000">warning</font> Resolution field &quot;@theia/core@0.7.1&quot; is incompatible with requested version &quot;@theia/core@^0.7.2&quot;
<font color="#C4A000">warning</font> Resolution field &quot;@theia/core@0.7.1&quot; is incompatible with requested version &quot;@theia/core@^0.7.2&quot;
<font color="#C4A000">warning</font> Resolution field &quot;@theia/core@0.7.1&quot; is incompatible with requested version &quot;@theia/core@^0.7.2&quot;
<font color="#C4A000">warning</font> Resolution field &quot;@theia/filesystem@0.7.1&quot; is incompatible with requested version &quot;@theia/filesystem@^0.7.2&quot;
<font color="#C4A000">warning</font> Resolution field &quot;@theia/filesystem@0.7.1&quot; is incompatible with requested version &quot;@theia/filesystem@^0.7.2&quot;
<font color="#8D8F8A">[2/4] Fetching packages...</font>
<font color="#CC0000">error</font> https://registry.yarnpkg.com/@material-ui/icons/-/icons-4.2.1.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: &quot;ENOENT: no such file or directory, chmod &apos;/home/philip/.cache/yarn/v4/npm-@material-ui-icons-4.2.1-fe2f1c4f60c24256d244a69d86d0c00e8ed4037e/node_modules/@material-ui/icons/AirportShuttleSharp.d.ts&apos;&quot;
<font color="#3465A4">info</font> Visit <b>https://yarnpkg.com/en/docs/cli/install</b> for documentation about this command.
</pre>

**Comment by eneufeld** [comment]
i will make this pr only contain the version update, this also contains renames which are broken and fixed with #91

**Comment by planger** [comment]
Ok, thanks! I tried building #91 too, but here I get this build error:
<pre>[<font color="#EF2929"><b>ERROR</b></font>] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module /home/philip/Git/OpenSource/coffee-editor/backend/releng/com.eclipsesource.coffee.parent/../../../../../Workspaces/coffee-editor/com.eclipsesource.emfforms.coffee.model of /home/philip/Git/OpenSource/coffee-editor/backend/releng/com.eclipsesource.coffee.parent/pom.xml does not exist @ </pre>

**Comment by eneufeld** [comment]
Yes, this is why it contains this comment: `Furthermore it needs the coffee model and must be changed to use the modelserver` ;-)
I need to ask @tortmayr about a consumable version of the coffee model from the modelserver

**Comment by planger** [comment]
Great, server builds now successfully! Client still fails (see below). I tried deleting the folder from the yarn cache, but the error persists. Do you have an idea what could be wrong here?

<pre><font color="#C4A000">warning</font> Resolution field &quot;@theia/filesystem@0.7.1&quot; is incompatible with requested version &quot;@theia/filesystem@^0.7.2&quot;
<font color="#C4A000">warning</font> Resolution field &quot;@theia/filesystem@0.7.1&quot; is incompatible with requested version &quot;@theia/filesystem@^0.7.2&quot;
<font color="#8D8F8A">[2/4] Fetching packages...</font>
<font color="#CC0000">error</font> https://registry.yarnpkg.com/@material-ui/icons/-/icons-4.2.1.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: &quot;ENOENT: no such file or directory, open &apos;/home/philip/.cache/yarn/v4/npm-@material-ui-icons-4.2.1-fe2f1c4f60c24256d244a69d86d0c00e8ed4037e/node_modules/@material-ui/icons/CameraFrontOutlined.js&apos;&quot;
<font color="#3465A4">info</font> Visit <b>https://yarnpkg.com/en/docs/cli/install</b> for documentation about this command.</pre>

**Comment by eneufeld** [comment]
Just try again

**Comment by eneufeld** [comment]
Yes we must update the example workspace. I suggest to do so as soon as we have merged #91

**Pull request merged**
