### PR TITLE
Update to latest glsp version

### PR DESCRIPTION
**Pull request by eneufeld**
* update example data
* update backend code to match model changes
* remove worklfow glsp code

### CODE REVIEW

**Comment by tortmayr** [comment]
Code looks good to me and I tested the GLSP editor with the SuperBrewer3000.wf file.  
I noticed some minor issues:
- SuperBrewer3001.wf has not been updated does not conform to the new SModel schema.
- web/readme.md is really outdated and should be updated or removed.

Unfortunately, I was not able to test the remaining features (Analyzer/Generator) because the maven build fails with 

: Execution default of goal org.eclipse.xtend:xtend-maven-plugin:2.14.0:compile failed: An API incompatibility was encountered while executing org.eclipse.xtend:xtend-maven-plugin:2.14.0:compile: java.lang.NoSuchMethodError: org.eclipse.jdt.internal.compiler.batch.FileSystem.getClasspath(Ljava/lang/String;Ljava/lang/String;ZLorg/eclipse/jdt/internal/compiler/env/AccessRuleSet;Ljava/lang/String;Ljava/util/Map;)Lorg/eclipse/jdt/internal/compiler/batch/FileSystem$Classpath;


(Same for Travis CI)

**Comment by eneufeld** [comment]
Thank you for the review, I will check the build errors as I didn't encounter those

**Comment by eneufeld** [comment]
@tortmayr could you retest?
I updated the poms.
The frontend build is still not working on travis. Locally it works for me. Any ideas?

**Comment by tortmayr** [comment]
I never run into this issue before. The problem seems to be related to the electron app. Maybe we should remove it since we only need the browser app anyways?

**Comment by planger** [comment]
I still can't open the workflow diagram. I think the wf file contains a wrong node type `node:task`.
```
16082 [pool-1-thread-1] DEBUG com.eclipsesource.glsp.server.jsonrpc.DefaultGLSPServer  - process ActionMessage [action=requestModel, clientId=widget-0]
May 17, 2019 9:08:30 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "process",
  "params": {
    "action": {
      "options": {
        "sourceUri": "file:///home/philip/Git/OpenSource/coffee-editor/backend/examples/SuperBrewer3000/SuperBrewer3000.wf",
        "diagramType": "workflow-diagram",
        "needsClientLayout": "true"
      },
      "kind": "requestModel"
    },
    "clientId": "widget-0"
  }
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:63)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:148)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:216)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:183)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:188)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:61)
	... 11 more
Caused by: java.lang.IllegalArgumentException: Unknown model type: node:task
	at com.eclipsesource.glsp.api.json.SModelElementTypeAdapter.createInstance(SModelElementTypeAdapter.java:42)
	at com.eclipsesource.glsp.api.json.SModelElementTypeAdapter.createInstance(SModelElementTypeAdapter.java:1)
	at org.eclipse.sprotty.server.json.PropertyBasedTypeAdapter.read(PropertyBasedTypeAdapter.java:60)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at org.eclipse.sprotty.server.json.PropertyBasedTypeAdapter.assignProperty(PropertyBasedTypeAdapter.java:86)
	at org.eclipse.sprotty.server.json.PropertyBasedTypeAdapter.read(PropertyBasedTypeAdapter.java:67)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at com.google.gson.Gson.fromJson(Gson.java:774)
	at com.eclipsesource.glsp.server.model.FileBasedModelFactory.loadModel(FileBasedModelFactory.java:56)
	at com.eclipsesource.glsp.server.actionhandler.RequestModelActionHandler.execute(RequestModelActionHandler.java:53)
	at com.eclipsesource.glsp.server.actionhandler.RequestModelActionHandler.execute(RequestModelActionHandler.java:45)
	at com.eclipsesource.glsp.api.diagram.DiagramManager.execute(DiagramManager.java:39)
	at com.eclipsesource.glsp.server.jsonrpc.DefaultGLSPServer.process(DefaultGLSPServer.java:100)
	... 16 more
```
I think, the task types have to be:
```
	public static final String MANUAL_TASK = "task:manual";
	public static final String AUTOMATED_TASK = "task:automated";
```

**Comment by eneufeld** [comment]
Which wf file cannot be opened for you?

**Comment by planger** [comment]
The wf file generated from the superbrewer 3000 jc.

**Comment by eneufeld** [comment]
did you rebuild the frontend after the pull of my latest changes?

**Comment by planger** [comment]
> did you rebuild the frontend after the pull of my latest changes?

Well, I ran `./run.sh -b -c -f`. @tortmayr does it work for you if you run `./run.sh -b -c -f` and then start the GLSP server from eclipse and then run `./run.sh -r`?

**Comment by eneufeld** [comment]
It worked for me when I fixed it and the reason was as you write the wrong node type

**Comment by planger** [comment]
I now retried and looked more closely into the logs. The reason it still fails is because the client build fails for me:
```
warning Pattern ["@theia/filesystem@next"] is trying to unpack in the same destination "/home/philip/.cache/yarn/v4/npm-@theia-filesystem-0.6.0-next.ed40d907-b251fb7b2fb64877ffea64113df9e7f4c1eb15a7/node_modules/@theia/filesystem" as pattern ["@theia/filesystem@0.6.0-next.ed40d907"]. This could result in non-deterministic behavior, skipping.
error https://registry.yarnpkg.com/@material-ui/icons/-/icons-3.0.2.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, chmod '/home/philip/.cache/yarn/v4/npm-@material-ui-icons-3.0.2-d67a6dd1ec8312d3a88ec97944a63daeef24fe10/node_modules/@material-ui/icons/AddAPhotoSharp.js'"
```

Unfortunately, cleaning `node_modules` and `~/.cache/yarn` didn't help.

@tortmayr If it works for you, we can merge this, I guess. Please let us know. Thanks!

**Comment by eneufeld** [comment]
@tortmayr  I fixed the SuperBrewer3001.wf file.

**Pull request merged**
